[project]
name = "jellyfin-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "beyChill", email = "74477178+beyChill@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
]

[project.scripts]
jellyfin-utils = "jellyfin_utils:main"

# [build-system]
# requires = ["uv_build>=0.12.3,<0.13.0"]
# build-backend = "uv_build"
